### ISSUE TITLE
Recommended way to pass fingerprinted filenames to HTML view?

### ISSUE THREAD

**Issue by cbosco** [moudy/broccoli-fingerprint#2]
Thanks for your work this is really handy.

I would be using this for cache busting and have a basic question: do you have a recommended approach for communicating out to a view, e.g. `index.html` the fingerprinted filename?

Maybe I am missing something obvious that is commonly used? I am used to rails asset pipeline for this which abstracts away the fingerprints.

**Comment by moudy** [comment]
@cbosco Thanks, glad you find it useful. I don't have a great solution for getting the filename ATM :(

You might find this project useful https://github.com/mjackson/broccoli-rev

I described my current solution here. It's not the most elegant but it works.
https://github.com/moudy/expressjs-base#assets-production

I read the all the file names from the assets directory
https://github.com/moudy/expressjs-base/blob/master/config/boot.js#L22

And then use a view helper in the the layout
https://github.com/moudy/expressjs-base/blob/master/lib/handlebars-helpers.js#L5
https://github.com/moudy/expressjs-base/blob/master/app/views/partials/foot.hbs#L1

**Comment by cbosco** [comment]
Thanks! feel free to close the issue unless it's something on your roadmap for the plugin

**Comment by moudy** [comment]
@cbosco I ended up adding `fingerprint.manifest` that outputs a json file mapping the original filenames to the fingerprinted ones (see readme example). It's not a complete solution but makes the logic in the view helper much cleaner.
